BookingEvents/Controllers/Event_TypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingEvents.Models;

namespace BookingEvents.Controllers
{
    public class Event_TypeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Event_Type
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Event_Type/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event_Type event_Type = db.Events.Find(id);
            if (event_Type == null)
            {
                return HttpNotFound();
            }
            return View(event_Type);
        }
        //Image
        //// Convert file to binary
        //public byte[] ConvertToBytes(HttpPostedFileBase file)
        //{
        //    BinaryReader reader = new BinaryReader(file.InputStream);
        //    return reader.ReadBytes((int)file.ContentLength);
        //}
        //Image
        //Display File
        //public FileStreamResult RenderImage(int id)
        //{
        //    MemoryStream ms = null;

        //    var item = db.Events.FirstOrDefault(x => x.EventId == id);
        //    if (item != null)
        //    {
        //        ms = new MemoryStream(item.Image);
        //    }
        //    return new FileStreamResult(ms, item.ImageType);
        //}
        // GET: Event_Type/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Event_Type/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,Image,EventName,BasicPrice")] Event_Type event_Type /*HttpPostedFileBase img_upload*/)
        {
            ////Image
            //if (img_upload != null && img_upload.ContentLength > 0)
            //{
            //    event_Type.ImageType = Path.GetExtension(img_upload.FileName);
            //    event_Type.Image = ConvertToBytes(img_upload);
            //}
            //
            if (ModelState.IsValid)
            {
                db.Events.Add(event_Type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(event_Type);
        }

        // GET: Event_Type/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event_Type event_Type = db.Events.Find(id);
            if (event_Type == null)
            {
                return HttpNotFound();
            }
            return View(event_Type);
        }

        // POST: Event_Type/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,EventName,BasicPrice")] Event_Type event_Type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(event_Type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(event_Type);
        }

        // GET: Event_Type/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event_Type event_Type = db.Events.Find(id);
            if (event_Type == null)
            {
                return HttpNotFound();
            }
            return View(event_Type);
        }

        // POST: Event_Type/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event_Type event_Type = db.Events.Find(id);
            db.Events.Remove(event_Type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingEvents/Views/Event_Type/Create.cshtml
@model BookingEvents.Models.Event_Type

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<br />
<br />
<br />
<h2 id="event">Add Event Type</h2>

@using (Html.BeginForm("Create", "Event_Type", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Event Type</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BasicPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BasicPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BasicPrice, "", new { @class = "text-danger" })
        </div>
    </div>
    @*@Html.LabelFor(model => model.Image)*@
    @*<td>
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-file-picture-o"></i>
            </div>
            <input type="file" name="img_upload" accept=".jpeg,.jpg,.png" onchange="readURL(this);" class="form-control" required="required" />
        </div>
    </td>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookingEvents/Views/Event_Type/Delete.cshtml
@model BookingEvents.Models.Event_Type

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event_Type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BasicPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasicPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookingEvents/Views/Event_Type/Details.cshtml
@model BookingEvents.Models.Event_Type

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event_Type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BasicPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasicPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BookingEvents/Views/Event_Type/Edit.cshtml
@model BookingEvents.Models.Event_Type

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event_Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BasicPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasicPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasicPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookingEvents/Views/Event_Type/Index.cshtml
@model IEnumerable<BookingEvents.Models.Event_Type>

@{
    ViewBag.Title = "Index";
}
<br id="event"/>
<br />
<br />
<br />
<br />
<h2 >List of event types</h2>

<p>
    @Html.ActionLink("Add new Event type ", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BasicPrice)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Image)
            </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BasicPrice)
        </td>
        @*<td>
            <img src="@Url.Action("RenderImage", "Event_Type", new { id = item.EventId})" width="50" height="60" />
        </td>*@
        <td>
            <a href="@Url.Action("Details","Event_Type", new { id=item.EventId })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs">Details<i class="fa fa-eye"></i></a>
            <a href="@Url.Action("Edit","Event_Type", new { id=item.EventId })" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs">Edit<i class="fa fa-edit"></i></a>
            <a href="@Url.Action("Delete", "Event_Type", new { id = item.EventId })" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">Delete<i class="fa fa-times"></i></a>
        </td>
    </tr>
}

</table>